local root = vim.uv.cwd()
local plugin = vim.env.HASKELL_DESIGN_TEST_PLUGIN or root
local work = root .. '/.test-output/neovim-' .. vim.fn.getpid()
vim.fn.mkdir(work .. '/Domain', 'p')
vim.fn.mkdir(work .. '/Application', 'p')
for _, file in ipairs({ 'Domain/Order.hs', 'Application/Checkout.hs', 'OrderSpec.hs' }) do
  vim.fn.writefile(vim.fn.readfile(plugin .. '/examples/' .. file), work .. '/' .. file)
end
vim.opt.runtimepath:prepend(plugin)
vim.cmd('runtime plugin/haskell-design.lua')
local hd = require('haskell-design')
-- Also cover setup when Lazy loads after the initial source has entered.
vim.cmd.edit(vim.fn.fnameescape(work .. '/Domain/Order.hs'))
local buf = vim.api.nvim_get_current_buf()
vim.bo[buf].modified = false
vim.o.hidden = false; vim.wo.number = true
hd.setup({ root = work, trusted = true, auto_verify = false, cache_dir = root .. '/.test-output/cache' })
local function wait_for(predicate, message, timeout)
  assert(vim.wait(timeout or 15000, predicate, 30), message)
end
local function text(b) return table.concat(vim.api.nvim_buf_get_lines(b, 0, -1, false), '\n') end
local function key(b, lhs)
  for _, entry in ipairs(vim.api.nvim_buf_get_keymap(b, 'n')) do if entry.lhs == lhs then entry.callback(); return end end
  error('mapping missing: ' .. lhs)
end
local function run()
  wait_for(function() return hd.views[vim.api.nvim_get_current_buf()] and hd.models[buf] end, 'default design did not open')
  local viewbuf = vim.api.nvim_get_current_buf()
  assert(hd.source_path() == work .. '/Domain/Order.hs', 'virtual view leaked its title as a path')
  if vim.env.HASKELL_DESIGN_TEST_MINI then
    vim.opt.runtimepath:prepend(vim.env.HASKELL_DESIGN_TEST_MINI)
    local files = require('mini.files')
    files.setup()
    files.open(hd.source_path(), true)
    assert(files.get_explorer_state(), 'mini.files did not open from design')
    files.close()
    assert(vim.api.nvim_get_current_buf() == viewbuf, 'file explorer did not restore design')
  end
  assert(#vim.api.nvim_list_wins() == 1, 'design created an auxiliary split')
  assert(hd.models[buf].status == 'unknown', 'unverified code was marked pure')
  assert(text(viewbuf):find('confirm ::', 1, true), 'signature missing')
  assert(not text(viewbuf):find('confirm order =', 1, true), 'body leaked into design')
  local line
  for row, decl in pairs(hd.views[viewbuf].mapping) do if decl.names[1] == 'confirm' then line = row; break end end
  assert(line, 'no source map')
  vim.api.nvim_win_set_cursor(0, { line, 0 }); key(viewbuf, 'za')
  assert(text(viewbuf):find('confirm order =', 1, true), 'implementation did not expand')
  hd.verify()
  wait_for(function() return hd.models[buf] and hd.models[buf].verified end, 'GHC verification did not finish', 60000)
  assert(hd.models[buf].status == 'pure', vim.inspect(hd.models[buf].issues))
  assert(text(viewbuf):find('Pure', 1, true), 'Pure label missing')
  assert(text(viewbuf):find('isDraft :: Order -> Bool', 1, true), 'inferred type missing')
  hd.files()
  local treebuf = vim.api.nvim_get_current_buf()
  wait_for(function() return hd.tree_views[treebuf].tree ~= nil end, 'folder tree missing')
  assert(vim.uv.fs_stat(hd.source_path()), 'folder view returned a nonexistent path')
  assert(text(treebuf):find('Domain/  [Pure 1]', 1, true), text(treebuf))
  assert(text(treebuf):find('Application/  [IO 1]', 1, true), text(treebuf))
  assert(text(treebuf):find('[IO 1 · 未解析 1 · Pure 1]', 1, true), 'root aggregate missing')
  -- An unavailable workspace must not leave its old Pure folder certified.
  -- Windows locks watched directories, so this Unix fault injection cannot run.
  if vim.fn.has('win32') == 0 then
  local moved = work .. '-moved'
  assert(vim.uv.fs_rename(work, moved))
  hd.refresh()
  local expired = vim.wait(15000, function() return hd.tree_views[treebuf].tree.summary.complete == false end, 30)
  assert(vim.uv.fs_rename(moved, work))
  assert(expired, 'failed folder scan retained old completeness')
  assert(not text(treebuf):find('Pure', 1, true), 'failed folder scan retained Pure')
  hd.refresh()
  wait_for(function() return text(treebuf):find('Domain/  [Pure 1]', 1, true) ~= nil end, 'folder did not recover after scan failure')
  else print('SKIP workspace-rename fault injection: Windows directory locks') end
  key(treebuf, 'q'); assert(vim.api.nvim_get_current_buf() == viewbuf)
  hd.source()
  assert(vim.api.nvim_get_current_buf() == buf, 'source toggle did not restore original buffer')
  assert(vim.wo.number, 'source window options were lost')
  assert(vim.wait(250, function() return false end, 20) == false)
  assert(vim.api.nvim_get_current_buf() == buf, 'source immediately bounced back to design')
  local original = text(buf)
  vim.api.nvim_buf_set_lines(buf, -1, -1, false, { '', 'debug :: IO ()', 'debug = pure ()' })
  vim.api.nvim_exec_autocmds('TextChanged', { buffer = buf })
  hd.open()
  assert(vim.api.nvim_get_current_buf() == viewbuf)
  assert(vim.bo[buf].modified, 'unsaved source lost its dirty state')
  wait_for(function() return hd.models[buf].status == 'io' end, 'IO marker did not update')
  assert(not hd.models[buf].verified, 'old proof survived edits')
  hd.files()
  wait_for(function() return text(treebuf):find('Domain/  [IO 1]', 1, true) ~= nil end, 'folder did not reflect unsaved IO')
  key(treebuf, 'q'); hd.source(); vim.cmd('undo')
  assert(text(buf) == original, 'undo did not survive design round trip')
  vim.api.nvim_exec_autocmds('TextChanged', { buffer = buf })
  hd.open()
  wait_for(function() return hd.models[buf].status == 'unknown' end, 'undo resurrected proof')
  -- An in-flight parse must never steal focus after opening another file.
  hd.source(); hd.open()
  local other = vim.api.nvim_create_buf(true, false)
  vim.api.nvim_set_current_buf(other)
  vim.wait(350, function() return false end, 20)
  assert(vim.api.nvim_get_current_buf() == other, 'async parse stole focus')
  -- Editing a new file defaults to design. Diff mode stays native.
  vim.cmd.edit(vim.fn.fnameescape(work .. '/Application/Checkout.hs'))
  local io_buf = vim.api.nvim_get_current_buf()
  wait_for(function() return hd.views[vim.api.nvim_get_current_buf()] and hd.models[io_buf] end, 'new file did not default to design')
  assert(hd.models[io_buf].status == 'io')
  local io_view = vim.api.nvim_get_current_buf()
  local first_win = vim.api.nvim_get_current_win()
  hd.files()
  vim.cmd('vsplit')
  local second_win = vim.api.nvim_get_current_win()
  key(treebuf, 'q')
  assert(vim.api.nvim_get_current_buf() == io_view, 'cloned folder window has no return action')
  vim.api.nvim_set_current_buf(viewbuf)
  hd.files()
  vim.api.nvim_set_current_win(first_win); key(treebuf, 'q')
  assert(vim.api.nvim_get_current_buf() == io_view, 'folder return crossed windows')
  vim.api.nvim_set_current_win(second_win); key(treebuf, 'q')
  assert(vim.api.nvim_get_current_buf() == viewbuf, 'second window lost its folder return')
  vim.api.nvim_win_close(second_win, true)
  vim.api.nvim_set_current_win(first_win)
  vim.cmd('HaskellDesignEvidence')
  assert(#vim.fn.getqflist() > 0, 'IO evidence not exposed')
  vim.cmd('cclose'); hd.source()
  vim.cmd('diffsplit ' .. vim.fn.fnameescape(work .. '/OrderSpec.hs'))
  local diffbuf = vim.api.nvim_get_current_buf()
  vim.wait(250, function() return false end, 20)
  assert(vim.api.nvim_get_current_buf() == diffbuf and not hd.views[diffbuf], 'design hijacked diff: ' .. vim.inspect({ expected=diffbuf, actual=vim.api.nvim_get_current_buf(), diff=vim.wo.diff }))
  vim.cmd('diffoff')
  vim.api.nvim_set_current_buf(buf); hd.open()
  local original_tab = vim.api.nvim_get_current_tabpage()
  hd.diff()
  wait_for(function() return vim.api.nvim_get_current_tabpage() ~= original_tab and #vim.api.nvim_tabpage_list_wins(0) == 2 end, 'design diff did not open')
  for _, win in ipairs(vim.api.nvim_tabpage_list_wins(0)) do
    vim.api.nvim_set_current_win(win)
    local side = vim.api.nvim_get_current_buf()
    assert(hd.source_path() == work .. '/Domain/Order.hs', 'diff side leaked its title as a path')
    if vim.env.HASKELL_DESIGN_TEST_MINI then
      local files = require('mini.files')
      files.open(hd.source_path(), true)
      assert(files.get_explorer_state(), 'mini.files did not open from design diff')
      files.close()
      assert(vim.api.nvim_get_current_buf() == side, 'file explorer did not restore diff side')
    end
  end
  vim.cmd('tabclose')
  assert(vim.api.nvim_get_current_tabpage() == original_tab)
  local settings = work .. '/.haskell-design.json'
  vim.fn.writefile({ '{"version":1,"ghcOptions":[]}' }, settings)
  local config_buf = vim.fn.bufadd(settings); vim.fn.bufload(config_buf)
  vim.api.nvim_exec_autocmds('BufWritePost', { buffer = config_buf })
  hd.verify()
  wait_for(function() return hd.models[buf].verified end, 'configured verification did not finish', 60000)
  vim.api.nvim_buf_set_lines(config_buf, 0, -1, false, { '{"version":1,"ghcOptions":["-XUnsafe"]}' })
  vim.api.nvim_exec_autocmds('TextChanged', { buffer = config_buf })
  assert(not hd.models[buf].verified, 'unsaved compiler configuration retained Pure')
  hd.verify()
  assert(not hd.models[buf].verified, 'verification accepted unsaved configuration')
  vim.bo[config_buf].modified = false
  print('Neovim integration: default design, same-window toggle, dirty/undo retention, source options, folder IO/Pure, proof invalidation, focus races and diff passed')
end
local ok, err = xpcall(run, debug.traceback)
if not ok then io.stderr:write(err .. '\n'); vim.cmd('cquit 1') else vim.cmd('qa!') end
