local repo = vim.fs.normalize(vim.uv.cwd())
local work = repo .. '/.test-output/neovim-dirty-' .. vim.fn.getpid()
vim.fn.mkdir(work .. '/src', 'p')
vim.fn.writefile({ 'name: example', 'library', '  hs-source-dirs: src' }, work .. '/example.cabal')
vim.fn.writefile({ 'module A where', 'a :: Int', 'a = 1' }, work .. '/src/A.hs')
vim.fn.writefile({ 'module B where', 'import A', 'b = a' }, work .. '/src/B.hs')
vim.cmd.edit(work .. '/src/A.hs')
local buf = vim.api.nvim_get_current_buf()
vim.api.nvim_buf_set_lines(buf, 0, -1, false, { 'module A where', 'a :: IO ()', 'a = pure ()' })
vim.opt.runtimepath:prepend(vim.env.HASKELL_DESIGN_TEST_PLUGIN or repo)
local hd = require('haskell-design')
hd.setup({ root = work, trusted = true, design_first = false, ghc_path = vim.env.HASKELL_DESIGN_TEST_GHC or 'ghc', cache_dir = repo .. '/.test-output/cache' })
assert(vim.wait(15000, function() return hd.indices[work] and not hd.indices[work].pending end, 25))
assert(hd.file_status(work .. '/src/A.hs') == 'io', 'existing dirty overlay was not seeded')
assert(hd.file_status(work .. '/src/B.hs') ~= 'pure', 'initial dirty dependency received a disk proof')
assert(hd.indices[work].stats.checked == 0)
vim.cmd('bdelete!')
assert(vim.wait(15000, function() return not hd.indices[work].pending and hd.file_status(work) == 'pure' end, 25), ':bdelete! did not discard the dirty overlay')
vim.cmd.edit(work .. '/src/A.hs')
buf = vim.api.nvim_get_current_buf()
vim.api.nvim_buf_set_lines(buf, 0, -1, false, { 'module A where', 'a :: IO ()', 'a = pure ()' })
vim.cmd('doautocmd TextChanged')
assert(vim.wait(15000, function() return not hd.indices[work].pending and hd.file_status(work .. '/src/A.hs') == 'io' and hd.file_status(work .. '/src/B.hs') ~= 'pure' end, 25))
vim.cmd('hide enew')
vim.wait(300)
assert(vim.api.nvim_buf_is_loaded(buf) and hd.file_status(work .. '/src/B.hs') ~= 'pure', 'hidden dirty buffer lost its overlay')
vim.cmd('bdelete! ' .. buf)
assert(vim.wait(15000, function() return not hd.indices[work].pending and hd.file_status(work) == 'pure' end, 25), 'discarding a hidden buffer blocked later verification')
vim.cmd.edit(work .. '/src/A.hs')
buf = vim.api.nvim_get_current_buf()
hd.open()
assert(vim.wait(15000, function() return hd.views[vim.api.nvim_get_current_buf()] ~= nil end, 25))
local design = vim.api.nvim_get_current_buf()
vim.cmd('bdelete! ' .. buf)
assert(not vim.api.nvim_buf_is_valid(design), 'source discard left its old Pure design visible')
vim.fn.writefile({ 'module A where', 'a :: IO ()', 'a = pure ()' }, work .. '/src/A.hs')
assert(vim.wait(15000, function() return not hd.indices[work].pending and hd.file_status(work .. '/src/A.hs') == 'io' end, 25))
print('Neovim existing dirty, hidden dirty and discarded dirty overlays: PASS')
vim.cmd('qa!')
